/**
 * Static inventory of financial assertions in verification scripts (Fix #22).
 */
export const FINANCIAL_ASSERTION_INVENTORY = [
  {
    file: "scripts/verify-sales-module.ts",
    function: "main / sale1 totals",
    value: "43500 / 13500 (was hardcoded)",
    represents: "Single-item sale total and profit",
    classification: "C — was unsafe; refactored to expectedSaleTotals()",
    action: "DERIVE from computeSalePreview",
  },
  {
    file: "scripts/verify-sales-module.ts",
    function: "main / stock after sales",
    value: "75 / 29 (was hardcoded)",
    represents: "Remaining stock after certification sales",
    classification: "C — was unsafe; refactored to expectedRemainingStock()",
    action: "DERIVE from initial stock − sold quantities",
  },
  {
    file: "scripts/verify-purchasing-module.ts",
    function: "main / purchase1.totalCost",
    value: "90000 (was hardcoded)",
    represents: "Purchase order total",
    classification: "C — was unsafe; refactored to expectedPurchaseTotalCost()",
    action: "DERIVE quantity × buyingPrice",
  },
  {
    file: "scripts/verify-purchasing-module.ts",
    function: "merge line items",
    value: "12200 (was hardcoded)",
    represents: "Weighted average buying price after merge",
    classification: "C — was unsafe; refactored to expectedMergedBuyingPrice()",
    action: "DERIVE from line inputs",
  },
  {
    file: "scripts/verify-branch-isolation.ts",
    function: "salaamaDbCount === 15",
    value: "752000",
    represents: "Assumed Salaama inventory value from seed/production",
    classification: "C — UNSAFE production assumption",
    action: "REMOVED — use salaamaDbValue from PostgreSQL",
  },
  {
    file: "scripts/verify-expenses-module.ts",
    function: "expectedTotal",
    value: "DB reduce sum",
    represents: "Expense certification totals",
    classification: "B — Dynamic database-derived",
    action: "KEEP",
  },
  {
    file: "scripts/verify-daily-operations-module.ts",
    function: "metrics / closePayload",
    value: "baseline + saleAmount − expenses",
    represents: "Close-day cash and summary",
    classification: "B — Dynamic from controlled inputs",
    action: "KEEP",
  },
  {
    file: "scripts/verify-reports-aggregation.ts",
    function: "runScenario fixtures",
    value: "50000, 1000, etc.",
    represents: "Controlled mock entry inputs",
    classification: "A — Safe test fixture expectation",
    action: "KEEP inputs; derive expected totals via expectedReportTotalsFromEntries",
  },
  {
    file: "scripts/verify-reports-module.ts",
    function: "historicalSummary totals",
    value: "1480000 / 1061500 / 418500 (was hardcoded)",
    represents: "Assumed historical import totals from production seed",
    classification: "C — UNSAFE production assumption",
    action: "REMOVED — derive from PostgreSQL entries via expectedReportTotalsFromEntries",
  },
  {
    file: "scripts/verify-reports-module.ts",
    function: "historicalEntries.length",
    value: "38 (was hardcoded)",
    represents: "Assumed historical day count from seed",
    classification: "C — UNSAFE production assumption",
    action: "REMOVED — assert historicalEntries.length > 0 only",
  },
  {
    file: "scripts/verify-bootstrap.ts",
    function: "dailyWage",
    value: "10000",
    represents: "Certification cashier fixture wage",
    classification: "A — Safe test fixture",
    action: "KEEP",
  },
  {
    file: "scripts/verify-reports-aggregation.ts",
    function: "assertBranchShape",
    value: "typeof number",
    represents: "Structural type checks only",
    classification: "E — Structural assertion",
    action: "KEEP",
  },
] as const;
