#!/usr/bin/env bash
# Idempotent repository bootstrap for the Sonic OS Cloud Agent environment.
# Installs and initializes a local PostgreSQL, prepares .env, installs Node
# dependencies, applies Prisma migrations, and seeds the database.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[install] Ensuring PostgreSQL is installed..."
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

PG_VERSION="$(pg_lsclusters -h 2>/dev/null | awk 'NR==1{print $1}')"
PG_VERSION="${PG_VERSION:-16}"

echo "[install] Starting PostgreSQL cluster ${PG_VERSION}/main..."
sudo pg_ctlcluster "${PG_VERSION}" main start || true

echo "[install] Waiting for PostgreSQL to accept connections..."
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "[install] Ensuring 'sonic' role and 'sonic_os' database exist..."
sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sonic') THEN
    CREATE ROLE sonic LOGIN PASSWORD 'sonic';
  END IF;
END $$;
ALTER ROLE sonic CREATEDB;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='sonic_os'" | grep -q 1; then
  sudo -u postgres createdb -O sonic sonic_os
fi

echo "[install] Ensuring .env exists..."
if [ ! -f .env ]; then
  SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  cat > .env <<ENV
# Local development environment for Sonic OS (generated by .cursor/install.sh)
APP_ENV=development
NODE_ENV=development
DATABASE_URL=postgresql://sonic:sonic@localhost:5432/sonic_os?schema=public
SESSION_SECRET=${SECRET}
NEXT_PUBLIC_USE_API=true
PORT=3000
HOSTNAME=0.0.0.0
ENV
fi

echo "[install] Installing Node dependencies..."
npm ci

echo "[install] Applying database migrations..."
npx prisma migrate deploy

echo "[install] Seeding database..."
npm run db:seed

echo "[install] Done."
