import { AUDIT_LOG_STORAGE_KEY } from "@/lib/audit-log/constants";
import {
  ACTIVE_BRANCH_STORAGE_KEY,
  ACTIVITY_LOG_STORAGE_KEY,
  AUTH_AUDIT_STORAGE_KEY,
  BRANCHES_STORAGE_KEY,
  DAY_CLOSINGS_STORAGE_KEY,
  EXPENSES_CATEGORIES_STORAGE_KEY,
  EXPENSES_RECORDS_STORAGE_KEY,
  EXPENSE_TEMPLATES_STORAGE_KEY,
  IMPORT_UNDO_STORAGE_KEY,
  NOTIFICATIONS_STORAGE_KEY,
  PURCHASING_PURCHASES_STORAGE_KEY,
  PURCHASING_SUPPLIERS_STORAGE_KEY,
  SALES_CUSTOMERS_STORAGE_KEY,
  SALES_STORAGE_KEY,
  SESSION_STORAGE_KEY,
  SETTINGS_STORAGE_KEY,
  STAFF_AUDIT_STORAGE_KEY,
  STAFF_PAYMENTS_STORAGE_KEY,
  STAFF_STORAGE_KEY,
  STOCK_ACTIVE_BRANCH_STORAGE_KEY,
  STOCK_LAST_MOVEMENT_BRANCH_STORAGE_KEY,
  STOCK_MOVEMENTS_STORAGE_KEY,
  STOCK_PRICE_CHANGES_STORAGE_KEY,
  STOCK_PRODUCTS_STORAGE_KEY,
  STORAGE_KEY,
  USERS_STORAGE_KEY,
} from "@/lib/constants";
import { removeLocalStorageItem } from "@/lib/safe-storage";

/** Legacy keys that must never restore auth, branch, or business authority. */
export const SECURITY_SENSITIVE_STORAGE_KEYS = [
  SESSION_STORAGE_KEY,
  USERS_STORAGE_KEY,
  AUTH_AUDIT_STORAGE_KEY,
  STAFF_STORAGE_KEY,
  SETTINGS_STORAGE_KEY,
  EXPENSE_TEMPLATES_STORAGE_KEY,
  DAY_CLOSINGS_STORAGE_KEY,
  AUDIT_LOG_STORAGE_KEY,
  STAFF_AUDIT_STORAGE_KEY,
  BRANCHES_STORAGE_KEY,
  ACTIVITY_LOG_STORAGE_KEY,
  NOTIFICATIONS_STORAGE_KEY,
  IMPORT_UNDO_STORAGE_KEY,
  STOCK_LAST_MOVEMENT_BRANCH_STORAGE_KEY,
  STOCK_ACTIVE_BRANCH_STORAGE_KEY,
  ACTIVE_BRANCH_STORAGE_KEY,
  STORAGE_KEY,
  SALES_STORAGE_KEY,
  SALES_CUSTOMERS_STORAGE_KEY,
  EXPENSES_RECORDS_STORAGE_KEY,
  EXPENSES_CATEGORIES_STORAGE_KEY,
  STAFF_PAYMENTS_STORAGE_KEY,
  PURCHASING_PURCHASES_STORAGE_KEY,
  PURCHASING_SUPPLIERS_STORAGE_KEY,
  STOCK_PRODUCTS_STORAGE_KEY,
  STOCK_MOVEMENTS_STORAGE_KEY,
  STOCK_PRICE_CHANGES_STORAGE_KEY,
] as const;

export type SecuritySensitiveStorageKey =
  (typeof SECURITY_SENSITIVE_STORAGE_KEYS)[number];

export function getSecuritySensitiveStorageKeyInventory(): readonly SecuritySensitiveStorageKey[] {
  return SECURITY_SENSITIVE_STORAGE_KEYS;
}

export function purgeSecuritySensitiveClientStorage(): void {
  for (const key of SECURITY_SENSITIVE_STORAGE_KEYS) {
    removeLocalStorageItem(key);
  }
}
